---
# This playbook will install mariadb and create db user and give permissions.

- name: Install Mariadb package
  apt: name={{ item }} state=installed
  with_items:
    - python-mysqldb
    - mariadb-server
    - mariadb-client

- name: Change root user password
  mysql_user:
    login_user=root
    login_password=
    user=root
    password=rootpass
    priv=*.*:ALL,GRANT
    state=present
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes

- name: Create Mariadb configuration file
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Create Application DB User
  mysql_user: name=appuser password=apppass priv=*.*:ALL host='%' state=present
