---
# This playbook will install mariadb and create db user and give permissions.

- name: Install software-properties-common
  apt: name=software-properties-common state=installed

- name: Add MariaDb repo key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0xcbcb082a1bb943db

- name: Add MariaDB repo
  apt_repository: 
    repo='deb http://mirror.netinch.com/pub/mariadb/repo/10.1/ubuntu trusty main'
    state=present

# Galera is merged into MariaDB server, MariaDB 10.1.1 binaries automatically support Galera out of the box.
- name: Install Mariadb package
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - python-mysqldb
    - mariadb-server

- name: Change root user password
  mysql_user:
    login_user=root
    login_password=
    user=root
    password={{ root_password }}
    priv=*.*:ALL,GRANT
    state=present
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes

- name: Create Mariadb configuration file
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: remove the test database
  mysql_db: name=test state=absent

- name: ensure anonymous users are not in the database
  mysql_user: 
    name=''
    state=absent
    host=host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create app db
  mysql_db: name={{ db_name }} state=present

- name: Create Application DB User
  mysql_user: 
    name={{ app_username }} 
    password={{ app_password }} 
    priv=*.*:ALL host='%' 
    state=present
