---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  apt: name={{ item }} state=installed
  with_items:
    - mysql-server
    - python-mysqldb
    - mysql-client

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present
  sudo: yes

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
