---
# These tasks install http and the php modules.

- name: Install http and php etc
  apt: name={{ item }} state=present
  with_items:
   - apache2
   - php5
   - php5-mysql
   - git

- name: apache2 service state
  service: name=apache2 state=started enabled=yes
