---
# Installs GUI and other stuff for web development

- name: Install base items
  apt: name={{ item }} state=installed
  with_items:
    - software-properties-common
    - vim 
    - tmux 
    - curl 
    - wget 
    - build-essential 
    - python-software-properties
    - htop

- name: Install desktop
  apt: name=ubuntu-desktop install_recommends=no state=installed

- name: add ST3 repo
  apt_repository: 
    repo='ppa:webupd8team/sublime-text-3'
    state=present

- name: Install ST3
  apt: name=sublime-text-installer state=installed

- name: Add chrome repo key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Add chrome repo
  apt_repository: 
    repo='deb http://dl.google.com/linux/chrome/deb/ stable main'
    state=present

- name: Install chrome
  apt: name=google-chrome-beta state=installed

- name: localize
  apt: name=language-pack-fi state=installed

- name: Create locale file
  file: src=locale dest=/etc/default/locale 

- name: Create keyboard file
  file: src=keyboard dest=/etc/default/keyboard

- name: trigger keyboard settings 1
  command: udevadm trigger --subsystem-match=input --action=change

- name: Create timezone file
  file: src=timezone dest=/etc/timezone

- name: trigger timezone settings
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart cron
  service: name=cron state=restarted

- name: add php repo
  apt_repository:
    repo='ppa:ondrej/php5'
    state=present

- name: add git repo
  apt_repository:
    repo='ppa:pdoes/ppa'
    state=present

- name: install latest nodejs 1
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: install latest nodejs 2
  command: apt-get install -y nodejs

- name: install common items
  apt: name={{ item }} state=installed
  with_items:
    - git 
    - php5 
    - apache2 
    - libapache2-mod-php5 
    - php5-mysql 
    - php5-curl 
    - php5-gd 
    - php5-mcrypt 
    - php5-xdebug 
    - nodejs

- name: download phpunit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=0770

- name: install memcached
  apt: name={{ item }} state=installed
  with_items:
    - memcached
    - php5-memcached

- name: crete xdebug config
  file: src=xdebug.ini dest=/etc/php5/mods-available/xdebug.ini

- name: enable mod_rewrite
  apache2_module: state=present name=rewrite

- name: create vhost config
  copy: src=/home/vagrant/ansible-lamp/roles/devmachine/files/devsite.conf dest=/etc/apache2/sites-available/devsite.conf

- name: use development php.ini
  command: cp /usr/share/php5/php.ini-development /etc/php5/apache2/php.ini

- name: restart apache
  service: name=apache2 state=restarted

- name: install composer 1
  command: curl -sS https://getcomposer.org/installer

- name: install composer 2
  command: mv composer.phar /usr/local/bin/composer

- name: install bash-git-prompt
  git: 
    repo=https://github.com/magicmonty/bash-git-prompt.git 
    dest=/home/vagrant/.bash-git-prompt

- name: create .bashrc
  copy: src=.bashrc dest=/home/vagrant/.bashrc owner=vagrant group=vagrant mode=0770

- name: setup laravel
  composer: command='create-project laravel/laravel /var/www/devsite' prefer_dist=yes

- name: setup permissions to devsite
  file: path=/var/www/devsite owner=vagrant group=www-data mode=1770 recurse=yes

- name: disable default vhost
  command: a2dissite 000-default

- name: enable devsite vhost
  command: a2ensite devsite 

- name: restart apache
  service: name=apache2 state=restarted
